### ISSUE TITLE
Does this JDK support arm32 processor architecture?

### ISSUE THREAD

**Issue by zmsoft** [ibmruntimes/openj9-openjdk-jdk12#53]
Does this JDK support arm32 processor architecture?

**Comment by pshipton** [comment]
Short answer is no.

The longer answer is that this project is a copy of http://hg.openjdk.java.net/jdk-updates/jdk12u/ with changes to support building with a replacement virtual machine https://github.com/eclipse/openj9. I'm not sure if OpenJDK 12 supports arm32 or not, but OpenJ9 doesn't. While OpenJ9 does contain some preliminary arm32 support, it was never finished. Note there is ongoing work for aarch64 for Java 11. Whatever preliminary changes were done in https://github.com/ibmruntimes/openj9-openjdk-jdk11 to get arm32 building, may not have been ported to this repo.

The OpenJ9 issue for arm32 is https://github.com/eclipse/openj9/issues/53
